# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Doanh Bui Cao
title: Sophomore at Faculty of Computer Science, University of Information and Technology, VNU
email: caodoanh2001@gmail.com
website: caodoanh2001.github.io

# Social links
github_username:  caodoanh2001
# dribbble_username: jekyll
facebook_username: buicaodoanh
# flickr_username: jekyll
# instagram_username: caodoanhbui
linkedin_username: buicaodoanh
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Doanh. My current major is Computer Science, i'm interested in Computer Vision. So that i have been studying about it for my future career.

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Publications

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Be a human, I also have some hobbies and favorite activities after studying and working time:
  - Watch football
  - Some drink with friend

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
